# Generated by Django 2.1.2 on 2018-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Precio de Entrada'),
        ),
        migrations.AddField(
            model_name='movie',
            name='hours',
            field=models.CharField(default='00:00 m - 00:00 m', max_length=40, verbose_name='Intervalos de hora\n(Separe por [,])'),
        ),
    ]
