# Generated by Django 2.1.2 on 2018-11-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181117_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hours',
            field=models.CharField(default='00:00 m - 00:00 m', max_length=40, verbose_name='Intervalos de hora (Separe con comas , )'),
        ),
    ]
