# Generated by Django 2.1.2 on 2018-11-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventaEntrada', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
