# Generated by Django 2.1.2 on 2018-11-17 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20181117_0000'),
        ('ventaEntrada', '0002_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('date_movie', models.DateField()),
                ('lot', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Movie')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['date_movie'],
            },
        ),
    ]
