# Generated by Django 2.1.2 on 2018-11-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventaEntrada', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hour',
            field=models.CharField(default='**:**m - **:**m', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lot',
            field=models.IntegerField(default=0),
        ),
    ]
